### ISSUE TITLE
App crashes if there is not network connection.

### ISSUE THREAD

**Issue by smits** [Intermodalics/tango_ros#123]
**Observed behavior**
When starting the app if there is not wifi connection the app crashes

**Desired behavior**
The app should not crash and just mention that the ROS master is not reachable or something similar.

**Comment by smits** [comment]
Some additional logcat output:
```
FATAL EXCEPTION: AsyncTask #1
E/AndroidRuntime(21386): Process: eu.intermodalics.tango_ros_streamer, PID: 21386
E/AndroidRuntime(21386): java.lang.RuntimeException: An error occured while executing doInBackground()
E/AndroidRuntime(21386): 	at android.os.AsyncTask$3.done(AsyncTask.java:300)
E/AndroidRuntime(21386): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
E/AndroidRuntime(21386): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
E/AndroidRuntime(21386): 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
E/AndroidRuntime(21386): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
E/AndroidRuntime(21386): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime(21386): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime(21386): 	at java.lang.Thread.run(Thread.java:811)
E/AndroidRuntime(21386): Caused by: org.ros.exception.RosRuntimeException: No non-loopback interface found.
E/AndroidRuntime(21386): 	at org.ros.address.InetAddressFactory.filterInetAddresses(InetAddressFactory.java:74)
E/AndroidRuntime(21386): 	at org.ros.address.InetAddressFactory.newNonLoopback(InetAddressFactory.java:78)
E/AndroidRuntime(21386): 	at eu.intermodalics.tango_ros_streamer.RunningActivity.init(RunningActivity.java:302)
E/AndroidRuntime(21386): 	at eu.intermodalics.tango_ros_streamer.RunningActivity$6.doInBackground(RunningActivity.java:375)
E/AndroidRuntime(21386): 	at eu.intermodalics.tango_ros_streamer.RunningActivity$6.doInBackground(RunningActivity.java:372)
E/AndroidRuntime(21386): 	at android.os.AsyncTask$2.call(AsyncTask.java:288)
E/AndroidRuntime(21386): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/AndroidRuntime(21386): 	... 4 more
W/ActivityManager(  908):   Force finishing activity eu.intermodalics.tango_ros_streamer/.RunningActivity
```
