### ISSUE TITLE
Look into recurring crash

### ISSUE THREAD

**Issue by PerrineAguiar** [Intermodalics/tango_ros#323]
This crash seems  to occur when unbinding from the Tango Service, so when closing the app.

```
java.lang.IllegalArgumentException: 
  at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1044)
  at android.app.ContextImpl.unbindService(ContextImpl.java:1337)
  at android.content.ContextWrapper.unbindService(ContextWrapper.java:616)
  at eu.intermodalics.nodelet_manager.TangoInitializationHelper.unbindTangoService(TangoInitializationHelper.java:109)
  at eu.intermodalics.tango_ros_streamer.activities.RunningActivity.unbindFromTango(RunningActivity.java:503)
  at eu.intermodalics.tango_ros_streamer.activities.RunningActivity.access$2400(RunningActivity.java:79)
  at eu.intermodalics.tango_ros_streamer.activities.RunningActivity$12.onShutdown(RunningActivity.java:712)
  at org.ros.android.NodeMainExecutorService$2.run(NodeMainExecutorService.java:185)
  at org.ros.android.NodeMainExecutorService$2.run(NodeMainExecutorService.java:182)
  at org.ros.concurrent.EventDispatcher.loop(EventDispatcher.java:43)
  at org.ros.concurrent.CancellableLoop.run(CancellableLoop.java:56)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
  at java.lang.Thread.run(Thread.java:818)
```

**Comment by PerrineAguiar** [comment]
Could be related to #198.
